import { User, Client, Requirement, Project, Message, Task, KnowledgeCase, AppNotification } from "@/types";

// ── Ad account mock data ──────────────────────────────────────────────────────

export interface AdAccountRow {
  platform: string;
  account: string;
  spend: number;
  roi: number;
  ctr: number;
  conversions: number;
}

const AD_PLATFORMS = [
  { name: "Meta", prefix: "META" },
  { name: "Google Ads", prefix: "GAD" },
  { name: "TikTok", prefix: "TTK" },
  { name: "YouTube", prefix: "YTB" },
] as const;

export function generateAccountData(projectId: string): AdAccountRow[] {
  const seed = projectId.charCodeAt(projectId.length - 1);
  return AD_PLATFORMS.map((p, i) => ({
    platform: p.name,
    account: `${p.prefix}-${(seed + i * 17) % 900 + 100}`,
    spend: Math.round(20000 + (seed * (i + 1) * 7) % 50000),
    roi: parseFloat((1.0 + ((seed + i) % 20) / 10).toFixed(2)),
    ctr: parseFloat((2.0 + ((seed + i) % 15) / 10).toFixed(1)),
    conversions: Math.round(200 + (seed * i * 3) % 800),
  }));
}

export const MOCK_USERS: User[] = [
  { id: "u1", name: "商务小谢", email: "wang@synapse.demo", role: "BUSINESS" },
  { id: "u2", name: "商务小张", email: "zhang@synapse.demo", role: "BUSINESS" },
  { id: "u3", name: "优化师小郑", email: "li@synapse.demo", role: "OPTIMIZER" },
  { id: "u4", name: "优化师小陈", email: "chen@synapse.demo", role: "OPTIMIZER" },
  { id: "u5", name: "管理员", email: "admin@synapse.demo", role: "ADMIN" },
];

export const MOCK_CLIENTS: Client[] = [
  { id: "c1", name: "星辰游戏有限公司", industry: "手游", region: "北美", ownerId: "u1" },
  { id: "c2", name: "荣华电商科技", industry: "女装电商", region: "东南亚", ownerId: "u1" },
  { id: "c3", name: "快乐学堂", industry: "在线教育", region: "欧洲", ownerId: "u2" },
];

export const MOCK_REQUIREMENTS: Requirement[] = [
  {
    id: "r1",
    clientId: "c1",
    clientName: "星辰游戏有限公司",
    creatorId: "u1",
    creatorName: "商务小谢",
    assignedOptimizerId: "u3",
    assignedOptimizerName: "优化师小郑",
    rawInput: "我们想在北美推一款策略手游，ROI要到1.2，预算每天500美金，跑Facebook和Instagram",
    structuredData: {
      region: "北美",
      media_platform: "Facebook & Instagram",
      daily_budget_usd: 500,
      target_kpi: "ROI",
      target_roi: 1.2,
      product_type: "策略手游",
      campaign_objective: "用户获取",
      product_url: null,
      soft_kpi: "",
      test_period: "",
      third_party_tracking: "Adjust",
      attribution_model: "代投",
      expected_start_date: "",
      policy_notes: "",
      ambiguous_fields: [],
    },
    aiEvaluation: {
      success_rate: 72,
      confidence: "medium",
      risks: [
        { level: "high", description: "目标ROI 1.2 在北美手游中仅30%能达成，建议调整至1.0-1.1" },
        { level: "medium", description: "日预算$500偏低，数据积累周期可能延长至14天以上" },
      ],
      strategy_suggestions: [
        "测试期先用自动出价（Advantage+），宽泛定向收集数据，7天后切换手动出价",
        "初期素材准备5-8套：竖版视频（9:16）+ 正方形图片各半，重点测试游戏玩法展示类",
        "建议预算分配：80%用于已验证受众，20%用于探索新受众，每周优化一次",
      ],
      estimated_timeline: "7-14天见效",
      similar_case_hint: "类似策略手游北美以$300/天起量，ROI 1.0达成率约65%，3周后稳定",
    },
    status: "EVALUATING",
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "r2",
    clientId: "c2",
    clientName: "荣华电商科技",
    creatorId: "u1",
    creatorName: "商务小谢",
    assignedOptimizerId: "u4",
    assignedOptimizerName: "优化师小陈",
    rawInput: "双十一备战，东南亚TikTok，女装品类，ROAS要4以上，每天预算1000美金",
    structuredData: {
      region: "东南亚",
      media_platform: "TikTok",
      daily_budget_usd: 1000,
      target_kpi: "ROAS",
      target_roi: null,
      product_type: "女装",
      campaign_objective: "促销转化",
      product_url: null,
      soft_kpi: "",
      test_period: "2个月",
      third_party_tracking: "AppsFlyer",
      attribution_model: "代投",
      expected_start_date: "尽快",
      policy_notes: "",
      ambiguous_fields: [],
    },
    status: "IN_PROGRESS",
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "r3",
    clientId: "c3",
    clientName: "快乐学堂",
    creatorId: "u2",
    creatorName: "商务小张",
    assignedOptimizerId: "u3",
    assignedOptimizerName: "优化师小郑",
    rawInput: "欧洲推广英语课，Google Ads，CPA控制在20欧以内，预算每天300欧",
    structuredData: {
      region: "欧洲",
      media_platform: "Google Ads",
      daily_budget_usd: 320,
      target_kpi: "CPA",
      target_roi: null,
      product_type: "在线教育",
      campaign_objective: "用户注册",
      product_url: null,
      soft_kpi: "7日留存",
      test_period: "首月",
      third_party_tracking: "Firebase",
      attribution_model: "自投+代投",
      expected_start_date: "Q2",
      policy_notes: "",
      ambiguous_fields: [],
    },
    status: "COMPLETED",
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: "p1",
    requirementId: "r2",
    clientName: "荣华电商科技",
    industry: "女装电商",
    mediaPlatform: "TikTok",
    businessName: "商务小谢",
    optimizerName: "优化师小陈",
    status: "OPTIMIZING",
    budgetActual: 3240,
    roiActual: 1.08,
    totalRecharge: 5000,
    dailySpend: 320,
    dailyRecharge: 0,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "p2",
    requirementId: "r3",
    clientName: "快乐学堂",
    industry: "在线教育",
    mediaPlatform: "Google",
    businessName: "商务小张",
    optimizerName: "优化师小郑",
    status: "COMPLETED",
    budgetActual: 4480,
    roiActual: 1.31,
    totalRecharge: 6000,
    dailySpend: 580,
    dailyRecharge: 1000,
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "p3",
    requirementId: "r1",
    clientName: "星辰手游",
    industry: "手游",
    mediaPlatform: "Facebook",
    businessName: "商务小谢",
    optimizerName: "优化师小陈",
    status: "LAUNCHING",
    budgetActual: 1850,
    roiActual: 0.92,
    totalRecharge: 3000,
    dailySpend: 500,
    dailyRecharge: 500,
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "p4",
    requirementId: "r4",
    clientName: "闪耀珠宝",
    industry: "珠宝首饰",
    mediaPlatform: "Instagram",
    businessName: "商务小张",
    optimizerName: "优化师小郑",
    status: "STRATEGY",
    budgetActual: 720,
    roiActual: 1.55,
    totalRecharge: 2000,
    dailySpend: 180,
    dailyRecharge: 0,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const MOCK_MESSAGES: Message[] = [
  {
    id: "m1",
    projectId: "p1",
    senderId: "system",
    senderName: "系统",
    senderRole: "ADMIN",
    content: "需求已接单，项目正式启动",
    type: "SYSTEM",
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "m2",
    projectId: "p1",
    senderId: "u4",
    senderName: "优化师小陈",
    senderRole: "OPTIMIZER",
    content: "已收到需求，正在搭建广告账户，预计明天开始投放",
    type: "TEXT",
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000 + 30 * 60 * 1000).toISOString(),
  },
  {
    id: "m3",
    projectId: "p1",
    senderId: "u1",
    senderName: "商务小谢",
    senderRole: "BUSINESS",
    content: "好的，客户催得比较紧，麻烦尽快",
    type: "TEXT",
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "m4",
    projectId: "p1",
    senderId: "u4",
    senderName: "优化师小陈",
    senderRole: "OPTIMIZER",
    content: "@商务小谢 素材收到了吗？需要客户提供 1:1 和 9:16 两种比例的视频",
    type: "TEXT",
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "m5",
    projectId: "p1",
    senderId: "u1",
    senderName: "商务小谢",
    senderRole: "BUSINESS",
    content: "好的，我去催一下，今天下午给你。另外客户说预算可以追加到 $1500/天",
    type: "TEXT",
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
  },
];

export const MOCK_TASKS: Task[] = [
  { id: "t1", projectId: "p1", title: "搭建广告账户结构", assigneeName: "优化师小陈", completed: true },
  { id: "t2", projectId: "p1", title: "提交创意素材（1:1 + 9:16）", assigneeName: "商务小谢", completed: true },
  { id: "t3", projectId: "p1", title: "第一周数据报告", assigneeName: "优化师小陈", dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(), completed: false },
  { id: "t4", projectId: "p1", title: "客户月报沟通会议", assigneeName: "商务小谢", dueDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(), completed: false },
];

export const MOCK_KNOWLEDGE_CASES: KnowledgeCase[] = [
  {
    id: "k1",
    title: "手游北美Facebook用户获取",
    industry: "手游",
    mediaPlatform: "Facebook",
    region: "北美",
    budgetRange: "$300-800/天",
    targetKpi: "ROI",
    targetRoi: 1.0,
    actualRoi: 1.25,
    strategySummary: "测试期采用 Advantage+ 自动出价，宽泛受众快速收集数据。第7天切换手动出价，重点投放 25-34 岁男性游戏爱好者。素材以游戏实录短视频（15-30秒）效果最佳，CTR 平均 3.2%。",
    keyInsights: [
      "宽泛定向 + Advantage+ 在测试期优于精准定向",
      "游戏玩法展示类素材 CTR 高于品牌宣传类 40%",
      "预算在 $500/天 以上数据积累速度最优，低于此建议延长测试期",
    ],
    tags: ["手游", "Facebook", "北美", "ROI优化", "用户获取"],
    isHighlight: true,
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "k2",
    title: "女装电商东南亚TikTok爆品打法",
    industry: "女装电商",
    mediaPlatform: "TikTok",
    region: "东南亚",
    budgetRange: "$500-1500/天",
    targetKpi: "ROAS",
    targetRoi: undefined,
    actualRoi: 4.8,
    strategySummary: "采用达人混剪 + 产品展示各半的素材策略，印尼和越南市场单独建 Campaign。放量阶段日均预算增幅不超过 20%，避免学习期重置。",
    keyInsights: [
      "达人UGC素材比纯品牌素材 ROAS 高出 35%",
      "东南亚不同国家受众差异大，建议按国家分开测试",
      "大促期间（双11/618）提前2周建立账户权重",
    ],
    tags: ["女装", "TikTok", "东南亚", "ROAS", "大促"],
    isHighlight: true,
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "k3",
    title: "在线教育欧洲Google搜索投放",
    industry: "在线教育",
    mediaPlatform: "Google",
    region: "欧洲",
    budgetRange: "$200-400/天",
    targetKpi: "CPA",
    targetRoi: undefined,
    actualRoi: 1.31,
    strategySummary: "搜索广告为主，智能出价（tCPA）配合手动出价双管齐下。关键词以长尾词为主，每周更新否词列表。英语课类目竞争激烈，建议错峰投放（周末 CPM 降低 30%）。",
    keyInsights: [
      "长尾关键词转化率比宽泛词高 2-3 倍，且 CPC 更低",
      "每周更新否词是保持效果的关键操作",
      "欧洲市场 GDPR 合规，不建议使用再营销列表",
    ],
    tags: ["教育", "Google", "欧洲", "CPA", "搜索广告"],
    isHighlight: false,
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "k4",
    title: "金融App东南亚投放风险案例",
    industry: "金融",
    mediaPlatform: "Facebook",
    region: "东南亚",
    budgetRange: "$300-600/天",
    targetKpi: "CPA",
    targetRoi: undefined,
    actualRoi: 0.7,
    strategySummary: "金融类目政策严格，素材频繁被拒导致起量慢。建议提前3-5个工作日申请政策豁免，素材避免承诺收益。最终未达成 CPA 目标，作为风险提示案例保留。",
    keyInsights: [
      "金融类目需提前申请资质审核，周期约5-7个工作日",
      "素材中避免出现百分比收益、保本等表述",
      "建议评估时将金融客户成功率下调 20%",
    ],
    tags: ["金融", "Facebook", "东南亚", "风险案例", "政策合规"],
    isHighlight: false,
    createdAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "k5",
    title: "全球电商Meta Advantage+购物活动",
    industry: "综合电商",
    mediaPlatform: "Meta",
    region: "全球",
    budgetRange: "$800-2000/天",
    targetKpi: "ROAS",
    targetRoi: undefined,
    actualRoi: 3.2,
    strategySummary: "使用 Advantage+ Shopping Campaign（ASC）全自动化投放，适合 SKU 数量超过 200 的电商客户。系统会自动选择最优受众和素材组合。",
    keyInsights: [
      "ASC 适合 SKU 多、数据积累充足的成熟账户",
      "新账户建议先用手动模式建立数据，3个月后切换 ASC",
      "全球化投放时可设置地区出价调整，高竞争地区可降低出价",
    ],
    tags: ["电商", "Meta", "全球", "ROAS", "ASC"],
    isHighlight: false,
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const MOCK_NOTIFICATIONS: AppNotification[] = [
  {
    id: "n1",
    type: "NEW_REQUIREMENT",
    title: "新需求待评估",
    body: "商务小谢提交了星辰游戏的北美投放需求，请尽快评估",
    read: false,
    link: "/requirements/r1",
    createdAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
  },
  {
    id: "n2",
    type: "EVAL_DONE",
    title: "AI 评估已完成",
    body: "荣华电商的东南亚需求评估完成，成功率 68%，可查看详情",
    read: false,
    link: "/requirements/r2",
    createdAt: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
  },
  {
    id: "n3",
    type: "ACCEPTED",
    title: "优化师已接单",
    body: "优化师小郑接受了你的广告需求，项目正式启动",
    read: true,
    link: "/projects/p1",
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "n4",
    type: "FOLLOW_UP",
    title: "优化师有追问",
    body: "优化师小郑对星辰游戏需求提出追问：目标受众年龄段是否有限制？",
    read: true,
    link: "/requirements/r1",
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
];
